services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: spring-app-container
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  mysql_data:
